version: 2

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    registries:
      - jfrog-artifactory

registries:
  jfrog-artifactory:
    type: "maven-repository"
    url: "https://jfrogghdemo.jfrog.io/artifactory/e2e-tests-dependabot-maven-repo/"
    username: "${{ secrets.MAVEN_USERNAME }}"
    password: "${{ secrets.MAVEN_PASSWORD }}"
    replaces-base: true
